### ISSUE TITLE
model_name is defined by Active Record

### ISSUE THREAD

**Issue by adslyw** [celsodantas/protokoll#16]
ActiveRecord::DangerousAttributeError: model_name is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.

**Comment by eduard-io** [comment]
@celsodantas the issue happens when upgrading to rails 4.2.0. The problem is that now it's not possible to have an attribute named `model_name` as it's reserved. See https://github.com/rails/rails/issues/18338#issuecomment-68695841 for details :)

**Comment by celsodantas** [comment]
lol. thanks @eduard-io , I'll fix it
Guess this will be a big API change =/
