### ISSUE TITLE
multi-process production environment

### ISSUE THREAD

**Issue by slemrmartin** [celsodantas/protokoll#27]
Hi, sorry, I don't know what do you mean with "github msg system" so I will ask here:

Does it work for production environment with multi-process app (ie. running on Nginx+Passenger).
How do you secure unique auto-incrementing value like "DOC001", "DOC002" etc.?

Thanks for response

**Comment by celsodantas** [comment]
The counting is done in the DB and it should work in te multi-process app.

I'm not using this project anymore, so I can't guarantee there isn't race condition. 
This is the spot where it increases the counter: https://github.com/celsodantas/protokoll/blob/master/lib/protokoll/counter.rb#L9-L13

PRs are welcome if you find anything worth fixing.
