### ISSUE TITLE
undefined method `model_name' for

### ISSUE THREAD

**Issue by satish-zol** [celsodantas/protokoll#30]
Hi there,

Not able to save model. getting this error 
`NoMethodError: undefined method `model_name' for #<PurchaseInvoice:0x0055a1bb3cb9e8>`
using ruby 2.3.0 and rails 4.1.6

Please do some helpful

Thanks

**Comment by celsodantas** [comment]
The `PurchaseInvoice` a ActiveRecord object? It is, it might be a issue with that Rails version.

Try running you code in the console and `PurchaseInvoice.model_name` and see if you get anything. It should return an `ActiveModel::Name` object

**Comment by satish-zol** [comment]
I just rename the column 'model_name' and it works fine!

**Comment by celsodantas** [comment]
sweet!
