### ISSUE TITLE
Dynamic pattern on the same model

### ISSUE THREAD

**Issue by mkhairi** [celsodantas/protokoll#31]
How can i implement something like this bellow?

```
  protokoll :request_no, pattern: dynamic_pattern, scope_by: :requestable_type
  
  def dynamic_pattern
    "RQ#{requestable_type}%Y%m####"
  end
```

**Comment by emaxi** [comment]
Hi @mkhairi, It's not possible to use ruby methods(like fields getters) in the pattern definition

**Comment by celsodantas** [comment]
sorry, closing this issue as this ia feature request.
