### ISSUE TITLE
Feature : scoped auto increment

### ISSUE THREAD

**Issue by geekvijay** [celsodantas/protokoll#9]

**Comment by zeeraw** [comment]
Have you already done work on this @celsodantas? Or is it up for grabs?

**Comment by celsodantas** [comment]
I haven't had the need for this feature, so I haven't started to work on it.
Feel free to work on it. =)

**Comment by alec-c4** [comment]
+100 x :+1: for scoped auto increment :) and is it possible to start counter from some predefined value?

**Comment by celsodantas** [comment]
No, @alec-c4 , not yet at least.

PRs are welcome =D

**Comment by emaxi** [comment]
Not sure if #25 is what you are looking for, but it worked to me generate pattern dynamically through a lambda for example

**Comment by celsodantas** [comment]
closing this as @emaxi PR implements the requested feature. (thanks @emaxi !)
